name: Auto Approve PRs

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    runs-on: macos-latest
    if: ${{ startsWith(github.head_ref, 'checks') }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Tag
        run: |
          set -euo pipefail
          git tag 0.0.1

      - name: Push Tag to Remote Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git push origin 0.0.1

      - name: Auto Approve PRs
        if: github.actor == 'swiftanon'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.payload.pull_request.number;
            
            // Ensure the pull request number is available
            if (!pr_number) {
              throw new Error("Pull request number not found in the context.");
            }

            // Use the Github API to create a review            
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              event: 'APPROVE'
            });